### ISSUE TITLE
Why the switch from Arc to Box?

### ISSUE THREAD

**Issue by jnicholls** [TrueLayer/reqwest-middleware#139]
In the commit to support reqwest 0.12, another breaking change was made: `Arc` -> `Box`. Why was this change made? I thought the point of the `with_arc` API was to be able to maintain a reference to a `Middleware` that was also provided to the `reqwest_middleware::ClientBuilder`. A `Box` is not a "reference" and there can only be one copy of it, i.e. it's not cloneable unless what it owns is also clonable. I'm not sure I agree with this update, but let me know if I'm missing something. Thanks!

**Comment by conradludgate** [comment]
I didn't put much thought into it. Internally there used to be a `Box<[Arc<dyn Middleware>]>` which is cloned about quite often.

* https://docs.rs/reqwest-middleware/0.2.5/src/reqwest_middleware/client.rs.html#87
* https://docs.rs/reqwest-middleware/0.2.5/src/reqwest_middleware/client.rs.html#139

Because of all the cloning, I decided to flip it to be Arc<Box> instead of Box<Arc>.

I see three solutions here.

1. The one I'd lean towards is Arc<Arc> even if it's a bit silly, but prevents extra unnecessary allocations on each request.

2. An alternative is to implement Middleware for Arc and then you can use the regular with(...) api. This would mean there's an extra box around your middleware

3. Revert this particular change
