### ISSUE TITLE
Testing middleware implementations is difficult.

### ISSUE THREAD

**Issue by Wopple** [TrueLayer/reqwest-middleware#26]
## Motivations

I am trying to test my middleware implementation but I can't because I can't call `handle` because I can't construct a `Next`.

## Solution

Provide an easy-to-use mechanism for testing middleware implementations.

## Alternatives

Make `Next` public for construction so I can at least call `handle` myself.

**Comment by Wopple** [comment]
Thanks for the example.

I guess I don't understand the internals of this library to know why "calling `handle` directly would necessitate a real client." But I would have thought that testing the middleware would have been done with a mock client. Abstractly speaking, a client is a function from a request to a response. The middleware wraps the that "function" and decides whether or not to call it and how to process the response if any. I should be able to test the middleware without need of a server.

**Comment by tl-rodrigo-gryzinski** [comment]
`Next` is just a wrapper around a reqwest client, that's why ([source](https://github.com/TrueLayer/reqwest-middleware/blob/main/reqwest-middleware/src/middleware.rs#L74)). We use [wiremock](https://docs.rs/wiremock/latest/wiremock/) to spin up servers to test against, so yeah it's more work than strictly needed to test middleware.
We don't really have a use for this right now but a PR is welcome, if you're up for it. I can see how it'd be useful to have a test client that maps to a `Request -> Response` function

**Comment by Wopple** [comment]
Unfortunately, I don't have the bandwidth for that right now. I'll have to follow along your mock server example.
